### ISSUE TITLE
Merging after a fork

### ISSUE THREAD

**Issue by almost** [substack/hyperlog-index#3]
In the merge example the index seems to disregard one of the forks. So node3 (with n=101) isn't included in the sum for the merge node. Is it possible to have a more intelligent merge that doesn't just through away logs in one of the forks?

So the merge.js example ends up with VALUE=607 when I might instead of wanted 708.

Apologies if I'm totally misunderstanding this! Also sorry if this isn't the right place to ask the question.

**Comment by substack** [comment]
Yes, it does seem like that example should result in 708 (3+4+100+101+500), not 607.

**Comment by almost** [comment]
Is this a bug in the module or have I done something wrong/misunderstood something?

It seems like maybe a bug if you're agreeing that the result should be 708. I'm interested in helping fix it but I'm just not sure exactly how it was meant to work. I don't see where the merge can actually happen in the current API. It seems like the indexer callback should maybe get multiple tx arguments for multiple parents?

**Comment by substack** [comment]
This was a substantial bug in the architecture of this module. Building a p2p distributed adder was more difficult than I anticipated, but it works now under the massive rewrite: https://github.com/substack/hyperlog-index/blob/master/example/adder.js#L11-L40

**Comment by substack** [comment]
To bring back the transaction interface, I think a separate module that sits on top of hyperlog-index will be a better place.
