### ISSUE TITLE
Readme - delete db

### ISSUE THREAD

**Issue by tvedtorama** [substack/hyperlog-index#6]
Hi,

in the readme - you do a `rm -rf /tmp/db1`.  Won't this also delete the main db?  Should it be `/tmp/db1/i`?

I also have a bit hard time understanding what this lib does, except that it's very clever.  Is it right to say that it follows graph links to build a key/value store - which makes it eas(y|ier) to merge conflicting changes?

Is it a requirement that nodes holds the {k, v} structure, which will then be used to build the index?

**Comment by noffle** [comment]
Hi Jørgen,

> in the readme - you do a `rm -rf /tmp/db1`.  Won't this also delete
> the main db?  Should it be `/tmp/db1/i`?

You're right: `rm -rf /tmp/db1` will delete the DB *and* the index.
`/tmp/db1/i` is the right thing to delete. Feel up to sending a pull
request?

> I also have a bit hard time understanding what this lib does, except
> that it's very clever.  Is it right to say that it follows graph links
> to build a key/value store - which makes it eas(y|ier) to merge
> conflicting changes?

You're halfway right: it processes every node in the graph, but it
doesn't build a key-value store: that's extra gravy that the README
example provides. All the module does is call the `map` function on each
hyperlog node (exactly once). It's up to the module user to decide what
to do with the nodes processed.

> Is it a requirement that nodes holds the {k, v} structure, which will
> then be used to build the index?

Not at all. `node.value` is completely freeform: you can store whatever
you like in it.

Cheers!

**Comment by tvedtorama** [comment]
Thank you very much for this much clarifying example!  I might get time to do a PR for this, but wonder if it's OK to try to add a few short comments to the code example - or is this left "comment free" by policy?

On more thing, very much unrelated: If you have a large hyperlog, with lots of data in it, is it trivial to export a subset (sub-graph) of this to peers and replicate back and forth using only this subset?  ...then rebuild the index?  I'm thinking about ways to build a ultra simple, yet functional, distributed time/resource booking system, where the full history is not relevant for all peers.

**Comment by noffle** [comment]
> but wonder if it's OK to try to add a few short comments to the code example - or is this left "comment free" by policy?

No, feel free to add comments (which I see you did).

> On more thing, very much unrelated: If you have a large hyperlog, with lots of data in it, is it trivial to export a subset (sub-graph) of this to peers and replicate back and forth using only this subset? ...then rebuild the index? I'm thinking about ways to build a ultra simple, yet functional, distributed time/resource booking system, where the full history is not relevant for all peers.

It is *not*. This is my major attraction to hypercore and [hyperdb](https://github.com/mafintosh/hyperdb): partial replication is possible.

**Comment by tvedtorama** [comment]
Thank you for this great feedback!
